/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";


export interface ScreenPropsByPath {
  "/": {
    context: unknown;
  };
  "/users/:userId": {
    context: {
      user: {
        id: string;
        name?: string;
      };
    };
  };
}

declare module "@tailorkit/app" {
  interface TailorKitScreens extends ScreenPropsByPath {}
}

export type ScreenPath = keyof ScreenPropsByPath & string;
export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];

export interface BoxProps {
  background?: "muted" | "surface" | {
    base?: "muted" | "surface";
    sm?: "muted" | "surface";
    md?: "muted" | "surface";
    lg?: "muted" | "surface";
    xl?: "muted" | "surface";
    "2xl"?: "muted" | "surface";
  };
  border?: "solid" | "dashed" | "dotted" | "double" | {
    base?: "solid" | "dashed" | "dotted" | "double";
    sm?: "solid" | "dashed" | "dotted" | "double";
    md?: "solid" | "dashed" | "dotted" | "double";
    lg?: "solid" | "dashed" | "dotted" | "double";
    xl?: "solid" | "dashed" | "dotted" | "double";
    "2xl"?: "solid" | "dashed" | "dotted" | "double";
  };
  borderColor?: "default" | {
    base?: "default";
    sm?: "default";
    md?: "default";
    lg?: "default";
    xl?: "default";
    "2xl"?: "default";
  };
  height?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
  margin?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  overflow?: "visible" | "hidden" | "clip" | "scroll" | "auto" | {
    base?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    sm?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    md?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    lg?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    xl?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    "2xl"?: "visible" | "hidden" | "clip" | "scroll" | "auto";
  };
  overflowWrap?: "normal" | "breakWord" | "anywhere" | {
    base?: "normal" | "breakWord" | "anywhere";
    sm?: "normal" | "breakWord" | "anywhere";
    md?: "normal" | "breakWord" | "anywhere";
    lg?: "normal" | "breakWord" | "anywhere";
    xl?: "normal" | "breakWord" | "anywhere";
    "2xl"?: "normal" | "breakWord" | "anywhere";
  };
  padding?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  radius?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  textAlign?: "left" | "right" | "start" | "end" | "center" | "justify" | {
    base?: "left" | "right" | "start" | "end" | "center" | "justify";
    sm?: "left" | "right" | "start" | "end" | "center" | "justify";
    md?: "left" | "right" | "start" | "end" | "center" | "justify";
    lg?: "left" | "right" | "start" | "end" | "center" | "justify";
    xl?: "left" | "right" | "start" | "end" | "center" | "justify";
    "2xl"?: "left" | "right" | "start" | "end" | "center" | "justify";
  };
  textOverflow?: "clip" | "ellipsis" | {
    base?: "clip" | "ellipsis";
    sm?: "clip" | "ellipsis";
    md?: "clip" | "ellipsis";
    lg?: "clip" | "ellipsis";
    xl?: "clip" | "ellipsis";
    "2xl"?: "clip" | "ellipsis";
  };
  textTransform?: "capitalize" | "uppercase" | "lowercase" | "none" | {
    base?: "capitalize" | "uppercase" | "lowercase" | "none";
    sm?: "capitalize" | "uppercase" | "lowercase" | "none";
    md?: "capitalize" | "uppercase" | "lowercase" | "none";
    lg?: "capitalize" | "uppercase" | "lowercase" | "none";
    xl?: "capitalize" | "uppercase" | "lowercase" | "none";
    "2xl"?: "capitalize" | "uppercase" | "lowercase" | "none";
  };
  width?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
}

export const Box = createRemoteComponent<BoxProps, readonly ["default"]>("Box", {
  slots: ["default"] as const,
});

export interface FlexProps {
  background?: "muted" | "surface" | {
    base?: "muted" | "surface";
    sm?: "muted" | "surface";
    md?: "muted" | "surface";
    lg?: "muted" | "surface";
    xl?: "muted" | "surface";
    "2xl"?: "muted" | "surface";
  };
  border?: "solid" | "dashed" | "dotted" | "double" | {
    base?: "solid" | "dashed" | "dotted" | "double";
    sm?: "solid" | "dashed" | "dotted" | "double";
    md?: "solid" | "dashed" | "dotted" | "double";
    lg?: "solid" | "dashed" | "dotted" | "double";
    xl?: "solid" | "dashed" | "dotted" | "double";
    "2xl"?: "solid" | "dashed" | "dotted" | "double";
  };
  borderColor?: "default" | {
    base?: "default";
    sm?: "default";
    md?: "default";
    lg?: "default";
    xl?: "default";
    "2xl"?: "default";
  };
  height?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
  margin?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  overflow?: "visible" | "hidden" | "clip" | "scroll" | "auto" | {
    base?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    sm?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    md?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    lg?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    xl?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    "2xl"?: "visible" | "hidden" | "clip" | "scroll" | "auto";
  };
  overflowWrap?: "normal" | "breakWord" | "anywhere" | {
    base?: "normal" | "breakWord" | "anywhere";
    sm?: "normal" | "breakWord" | "anywhere";
    md?: "normal" | "breakWord" | "anywhere";
    lg?: "normal" | "breakWord" | "anywhere";
    xl?: "normal" | "breakWord" | "anywhere";
    "2xl"?: "normal" | "breakWord" | "anywhere";
  };
  padding?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  radius?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  textAlign?: "left" | "right" | "start" | "end" | "center" | "justify" | {
    base?: "left" | "right" | "start" | "end" | "center" | "justify";
    sm?: "left" | "right" | "start" | "end" | "center" | "justify";
    md?: "left" | "right" | "start" | "end" | "center" | "justify";
    lg?: "left" | "right" | "start" | "end" | "center" | "justify";
    xl?: "left" | "right" | "start" | "end" | "center" | "justify";
    "2xl"?: "left" | "right" | "start" | "end" | "center" | "justify";
  };
  textOverflow?: "clip" | "ellipsis" | {
    base?: "clip" | "ellipsis";
    sm?: "clip" | "ellipsis";
    md?: "clip" | "ellipsis";
    lg?: "clip" | "ellipsis";
    xl?: "clip" | "ellipsis";
    "2xl"?: "clip" | "ellipsis";
  };
  textTransform?: "capitalize" | "uppercase" | "lowercase" | "none" | {
    base?: "capitalize" | "uppercase" | "lowercase" | "none";
    sm?: "capitalize" | "uppercase" | "lowercase" | "none";
    md?: "capitalize" | "uppercase" | "lowercase" | "none";
    lg?: "capitalize" | "uppercase" | "lowercase" | "none";
    xl?: "capitalize" | "uppercase" | "lowercase" | "none";
    "2xl"?: "capitalize" | "uppercase" | "lowercase" | "none";
  };
  width?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
  align?: "start" | "center" | "end" | "stretch" | {
    base?: "start" | "center" | "end" | "stretch";
    sm?: "start" | "center" | "end" | "stretch";
    md?: "start" | "center" | "end" | "stretch";
    lg?: "start" | "center" | "end" | "stretch";
    xl?: "start" | "center" | "end" | "stretch";
    "2xl"?: "start" | "center" | "end" | "stretch";
  };
  direction?: "row" | "column" | {
    base?: "row" | "column";
    sm?: "row" | "column";
    md?: "row" | "column";
    lg?: "row" | "column";
    xl?: "row" | "column";
    "2xl"?: "row" | "column";
  };
  gap?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  justify?: "start" | "center" | "end" | "between" | {
    base?: "start" | "center" | "end" | "between";
    sm?: "start" | "center" | "end" | "between";
    md?: "start" | "center" | "end" | "between";
    lg?: "start" | "center" | "end" | "between";
    xl?: "start" | "center" | "end" | "between";
    "2xl"?: "start" | "center" | "end" | "between";
  };
}

export const Flex = createRemoteComponent<FlexProps, readonly ["default"]>("Flex", {
  slots: ["default"] as const,
});

export interface GridProps {
  background?: "muted" | "surface" | {
    base?: "muted" | "surface";
    sm?: "muted" | "surface";
    md?: "muted" | "surface";
    lg?: "muted" | "surface";
    xl?: "muted" | "surface";
    "2xl"?: "muted" | "surface";
  };
  border?: "solid" | "dashed" | "dotted" | "double" | {
    base?: "solid" | "dashed" | "dotted" | "double";
    sm?: "solid" | "dashed" | "dotted" | "double";
    md?: "solid" | "dashed" | "dotted" | "double";
    lg?: "solid" | "dashed" | "dotted" | "double";
    xl?: "solid" | "dashed" | "dotted" | "double";
    "2xl"?: "solid" | "dashed" | "dotted" | "double";
  };
  borderColor?: "default" | {
    base?: "default";
    sm?: "default";
    md?: "default";
    lg?: "default";
    xl?: "default";
    "2xl"?: "default";
  };
  height?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
  margin?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  overflow?: "visible" | "hidden" | "clip" | "scroll" | "auto" | {
    base?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    sm?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    md?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    lg?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    xl?: "visible" | "hidden" | "clip" | "scroll" | "auto";
    "2xl"?: "visible" | "hidden" | "clip" | "scroll" | "auto";
  };
  overflowWrap?: "normal" | "breakWord" | "anywhere" | {
    base?: "normal" | "breakWord" | "anywhere";
    sm?: "normal" | "breakWord" | "anywhere";
    md?: "normal" | "breakWord" | "anywhere";
    lg?: "normal" | "breakWord" | "anywhere";
    xl?: "normal" | "breakWord" | "anywhere";
    "2xl"?: "normal" | "breakWord" | "anywhere";
  };
  padding?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  radius?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  textAlign?: "left" | "right" | "start" | "end" | "center" | "justify" | {
    base?: "left" | "right" | "start" | "end" | "center" | "justify";
    sm?: "left" | "right" | "start" | "end" | "center" | "justify";
    md?: "left" | "right" | "start" | "end" | "center" | "justify";
    lg?: "left" | "right" | "start" | "end" | "center" | "justify";
    xl?: "left" | "right" | "start" | "end" | "center" | "justify";
    "2xl"?: "left" | "right" | "start" | "end" | "center" | "justify";
  };
  textOverflow?: "clip" | "ellipsis" | {
    base?: "clip" | "ellipsis";
    sm?: "clip" | "ellipsis";
    md?: "clip" | "ellipsis";
    lg?: "clip" | "ellipsis";
    xl?: "clip" | "ellipsis";
    "2xl"?: "clip" | "ellipsis";
  };
  textTransform?: "capitalize" | "uppercase" | "lowercase" | "none" | {
    base?: "capitalize" | "uppercase" | "lowercase" | "none";
    sm?: "capitalize" | "uppercase" | "lowercase" | "none";
    md?: "capitalize" | "uppercase" | "lowercase" | "none";
    lg?: "capitalize" | "uppercase" | "lowercase" | "none";
    xl?: "capitalize" | "uppercase" | "lowercase" | "none";
    "2xl"?: "capitalize" | "uppercase" | "lowercase" | "none";
  };
  width?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit" | {
    base?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    sm?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    md?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    lg?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    xl?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
    "2xl"?: "0" | "1/2" | "1/3" | "2/3" | "1/4" | "2/4" | "3/4" | "1/5" | "2/5" | "3/5" | "4/5" | "1/6" | "2/6" | "3/6" | "4/6" | "5/6" | "1/12" | "2/12" | "3/12" | "4/12" | "5/12" | "6/12" | "7/12" | "8/12" | "9/12" | "10/12" | "11/12" | "full" | "min" | "max" | "fit";
  };
  columns?: number | {
    base?: number;
    sm?: number;
    md?: number;
    lg?: number;
    xl?: number;
    "2xl"?: number;
  };
  gap?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
}

export const Grid = createRemoteComponent<GridProps, readonly ["default"]>("Grid", {
  slots: ["default"] as const,
});

export interface InlineProps {
  background?: "muted" | "surface" | {
    base?: "muted" | "surface";
    sm?: "muted" | "surface";
    md?: "muted" | "surface";
    lg?: "muted" | "surface";
    xl?: "muted" | "surface";
    "2xl"?: "muted" | "surface";
  };
  borderColor?: "default" | {
    base?: "default";
    sm?: "default";
    md?: "default";
    lg?: "default";
    xl?: "default";
    "2xl"?: "default";
  };
  margin?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  overflowWrap?: "normal" | "breakWord" | "anywhere" | {
    base?: "normal" | "breakWord" | "anywhere";
    sm?: "normal" | "breakWord" | "anywhere";
    md?: "normal" | "breakWord" | "anywhere";
    lg?: "normal" | "breakWord" | "anywhere";
    xl?: "normal" | "breakWord" | "anywhere";
    "2xl"?: "normal" | "breakWord" | "anywhere";
  };
  padding?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  radius?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | {
    base?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    sm?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    md?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    lg?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    xl?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
    "2xl"?: "none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl";
  };
  textAlign?: "left" | "right" | "start" | "end" | "center" | "justify" | {
    base?: "left" | "right" | "start" | "end" | "center" | "justify";
    sm?: "left" | "right" | "start" | "end" | "center" | "justify";
    md?: "left" | "right" | "start" | "end" | "center" | "justify";
    lg?: "left" | "right" | "start" | "end" | "center" | "justify";
    xl?: "left" | "right" | "start" | "end" | "center" | "justify";
    "2xl"?: "left" | "right" | "start" | "end" | "center" | "justify";
  };
  textOverflow?: "clip" | "ellipsis" | {
    base?: "clip" | "ellipsis";
    sm?: "clip" | "ellipsis";
    md?: "clip" | "ellipsis";
    lg?: "clip" | "ellipsis";
    xl?: "clip" | "ellipsis";
    "2xl"?: "clip" | "ellipsis";
  };
  textTransform?: "capitalize" | "uppercase" | "lowercase" | "none" | {
    base?: "capitalize" | "uppercase" | "lowercase" | "none";
    sm?: "capitalize" | "uppercase" | "lowercase" | "none";
    md?: "capitalize" | "uppercase" | "lowercase" | "none";
    lg?: "capitalize" | "uppercase" | "lowercase" | "none";
    xl?: "capitalize" | "uppercase" | "lowercase" | "none";
    "2xl"?: "capitalize" | "uppercase" | "lowercase" | "none";
  };
}

export const Inline = createRemoteComponent<InlineProps, readonly ["default"]>("Inline", {
  slots: ["default"] as const,
});

export interface ButtonProps {
  variant?: "default" | "secondary" | "outline" | "ghost" | "destructive";
  onClick?: () => void;
}

export const Button = createRemoteComponent<ButtonProps, readonly ["default"]>("Button", {
  slots: ["default"] as const,
  callbacks: { "onClick": 0 },
});

export interface LinkProps {
  href?: string;
}

export const Link = createRemoteComponent<LinkProps, readonly ["default"]>("Link", {
  slots: ["default"] as const,
});

export interface InputProps {
  type?: "text" | "email" | "password";
  placeholder?: string;
  value?: string;
  disabled?: boolean;
  onChange?: () => void;
  onBlur?: () => void;
  onFocus?: () => void;
}

export const Input = createRemoteComponent<InputProps, readonly ["default"]>("Input", {
  slots: ["default"] as const,
  callbacks: { "onChange": 0, "onBlur": 0, "onFocus": 0 },
});

export interface TabsProps {
  defaultValue?: string;
  value?: string;
  onValueChange?: (value1: string) => void;
}

export const Tabs = createRemoteComponent<TabsProps, readonly ["default"]>("Tabs", {
  slots: ["default"] as const,
  callbacks: { "onValueChange": 1 },
});

export interface TabsListProps {
  variant?: "default" | "underline";
}

export const TabsList = createRemoteComponent<TabsListProps, readonly ["default"]>("TabsList", {
  slots: ["default"] as const,
});

export interface TabsTabProps {
  value?: string;
}

export const TabsTab = createRemoteComponent<TabsTabProps, readonly ["default"]>("TabsTab", {
  slots: ["default"] as const,
});

export interface TabsPanelProps {
  value?: string;
}

export const TabsPanel = createRemoteComponent<TabsPanelProps, readonly ["default"]>("TabsPanel", {
  slots: ["default"] as const,
});
