// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AppsCreateData,
  AppsCreateResponses,
  AppsDeleteData,
  AppsDeleteResponses,
  AppsDeployData,
  AppsDeployResponses,
  AppsGetData,
  AppsGetResponses,
  AppsListData,
  AppsListResponses,
  AppsUpdateData,
  AppsUpdateResponses,
  CliAuthApproveData,
  CliAuthApproveResponses,
  CliAuthDenyData,
  CliAuthDenyResponses,
  CliAuthPollData,
  CliAuthPollResponses,
  CliAuthStartData,
  CliAuthStartResponses,
  CliAuthVerifyTokenData,
  CliAuthVerifyTokenResponses,
  DeploymentsCreateData,
  DeploymentsCreateResponses,
  DeploymentsGetData,
  DeploymentsGetResponses,
  DeploymentsListData,
  DeploymentsListResponses,
  DeploymentsPublishData,
  DeploymentsPublishResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const appsList = <ThrowOnError extends boolean = false>(
  options: Options<AppsListData, ThrowOnError>,
) =>
  (options.client ?? client).get<AppsListResponses, unknown, ThrowOnError>({
    url: "/apps",
    ...options,
  });

export const appsCreate = <ThrowOnError extends boolean = false>(
  options: Options<AppsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<AppsCreateResponses, unknown, ThrowOnError>({
    url: "/apps",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsDelete = <ThrowOnError extends boolean = false>(
  options: Options<AppsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<AppsDeleteResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}",
    ...options,
  });

export const appsGet = <ThrowOnError extends boolean = false>(
  options: Options<AppsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<AppsGetResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}",
    ...options,
  });

export const appsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AppsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<AppsUpdateResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsDeploy = <ThrowOnError extends boolean = false>(
  options: Options<AppsDeployData, ThrowOnError>,
) =>
  (options.client ?? client).post<AppsDeployResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}/deploy",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthApprove = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthApproveData, ThrowOnError>,
) =>
  (options.client ?? client).post<CliAuthApproveResponses, unknown, ThrowOnError>({
    url: "/cli-auth/approve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthDeny = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthDenyData, ThrowOnError>,
) =>
  (options.client ?? client).post<CliAuthDenyResponses, unknown, ThrowOnError>({
    url: "/cli-auth/deny",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthPoll = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthPollData, ThrowOnError>,
) =>
  (options.client ?? client).post<CliAuthPollResponses, unknown, ThrowOnError>({
    url: "/cli-auth/poll",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthStart = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthStartData, ThrowOnError>,
) =>
  (options.client ?? client).post<CliAuthStartResponses, unknown, ThrowOnError>({
    url: "/cli-auth/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthVerifyToken = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthVerifyTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<CliAuthVerifyTokenResponses, unknown, ThrowOnError>({
    url: "/cli-auth/verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsList = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsListData, ThrowOnError>,
) =>
  (options.client ?? client).get<DeploymentsListResponses, unknown, ThrowOnError>({
    url: "/deployments",
    ...options,
  });

export const deploymentsCreate = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<DeploymentsCreateResponses, unknown, ThrowOnError>({
    url: "/deployments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsGet = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<DeploymentsGetResponses, unknown, ThrowOnError>({
    url: "/deployments/{deploymentId}",
    ...options,
  });

export const deploymentsPublish = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsPublishData, ThrowOnError>,
) =>
  (options.client ?? client).post<DeploymentsPublishResponses, unknown, ThrowOnError>({
    url: "/deployments/{deploymentId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
