// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://tailorkit.dev/api/platform" | (string & {});
};

export type AppsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    scopeId: string;
  };
  url: "/apps";
};

export type AppsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      projectId: string;
      scopeId: string;
      name: string;
      description: string | null;
      currentDeploymentId: string | null;
      createdAt: string;
      updatedAt: string;
      currentDeployment: {
        id: string;
        appId: string;
        status: "uploading" | "deploying" | "verifying" | "published";
        clientEntryFileId: string | null;
        createdAt: string;
        updatedAt: string;
      } | null;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type AppsListResponse = AppsListResponses[keyof AppsListResponses];

export type AppsCreateData = {
  body: {
    name: string;
    description: string | null;
    scopeId: string;
  };
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsCreateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    scopeId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
  };
};

export type AppsCreateResponse = AppsCreateResponses[keyof AppsCreateResponses];

export type AppsDeleteData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    scopeId: string;
  };
  url: "/apps/{appId}";
};

export type AppsDeleteResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type AppsDeleteResponse = AppsDeleteResponses[keyof AppsDeleteResponses];

export type AppsGetData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    scopeId: string;
  };
  url: "/apps/{appId}";
};

export type AppsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    scopeId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
  };
};

export type AppsGetResponse = AppsGetResponses[keyof AppsGetResponses];

export type AppsUpdateData = {
  body: {
    name: string;
    description: string | null;
  };
  path: {
    appId: string;
  };
  query: {
    scopeId: string;
  };
  url: "/apps/{appId}";
};

export type AppsUpdateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    scopeId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
  };
};

export type AppsUpdateResponse = AppsUpdateResponses[keyof AppsUpdateResponses];

export type AppsDeployData = {
  body: {
    deploymentId: string;
  };
  path: {
    appId: string;
  };
  query: {
    scopeId: string;
  };
  url: "/apps/{appId}/deploy";
};

export type AppsDeployResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    scopeId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
  };
};

export type AppsDeployResponse = AppsDeployResponses[keyof AppsDeployResponses];

export type CliAuthApproveData = {
  body: {
    scopeId: string;
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/approve";
};

export type CliAuthApproveResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthApproveResponse = CliAuthApproveResponses[keyof CliAuthApproveResponses];

export type CliAuthDenyData = {
  body: {
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/deny";
};

export type CliAuthDenyResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthDenyResponse = CliAuthDenyResponses[keyof CliAuthDenyResponses];

export type CliAuthPollData = {
  body: {
    deviceCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/poll";
};

export type CliAuthPollResponses = {
  /**
   * OK
   */
  200:
    | {
        status: "pending";
      }
    | {
        status: "denied";
      }
    | {
        deployToken: string;
        scopeId: string;
        status: "approved";
      }
    | {
        status: "expired";
      };
};

export type CliAuthPollResponse = CliAuthPollResponses[keyof CliAuthPollResponses];

export type CliAuthStartData = {
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/start";
};

export type CliAuthStartResponses = {
  /**
   * OK
   */
  200: {
    deviceCode: string;
    expiresAt: string;
    userCode: string;
  };
};

export type CliAuthStartResponse = CliAuthStartResponses[keyof CliAuthStartResponses];

export type CliAuthVerifyTokenData = {
  body: {
    deployToken: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/verify-token";
};

export type CliAuthVerifyTokenResponses = {
  /**
   * OK
   */
  200: {
    scopeId: string;
  };
};

export type CliAuthVerifyTokenResponse =
  CliAuthVerifyTokenResponses[keyof CliAuthVerifyTokenResponses];

export type DeploymentsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    appId: string;
    scopeId: string;
  };
  url: "/deployments";
};

export type DeploymentsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type DeploymentsListResponse = DeploymentsListResponses[keyof DeploymentsListResponses];

export type DeploymentsCreateData = {
  body: {
    appId: string;
    assets: [
      {
        contentType: "application/javascript";
        encoding: "utf-8";
        checksum: string;
        contentLength: number;
        objectKey: string;
      },
    ];
    scopeId: string;
  };
  path?: never;
  query?: never;
  url: "/deployments";
};

export type DeploymentsCreateResponses = {
  /**
   * OK
   */
  200: {
    assets: [
      {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "application/javascript";
          encoding: "utf-8";
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl: string;
      },
    ];
    deployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type DeploymentsCreateResponse =
  DeploymentsCreateResponses[keyof DeploymentsCreateResponses];

export type DeploymentsGetData = {
  body?: never;
  path: {
    deploymentId: string;
  };
  query: {
    scopeId: string;
  };
  url: "/deployments/{deploymentId}";
};

export type DeploymentsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsGetResponse = DeploymentsGetResponses[keyof DeploymentsGetResponses];

export type DeploymentsPublishData = {
  body: {
    scopeId: string;
    rollout?: boolean;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/deployments/{deploymentId}";
};

export type DeploymentsPublishResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsPublishResponse =
  DeploymentsPublishResponses[keyof DeploymentsPublishResponses];
