// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://tailorkit.dev/api/platform" | (string & {});
};

export type AppsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    resourceId: string;
  };
  url: "/apps";
};

export type AppsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      projectId: string;
      resourceId: string;
      name: string;
      description: string | null;
      currentDeploymentId: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type AppsListResponse = AppsListResponses[keyof AppsListResponses];

export type AppsCreateData = {
  body: {
    name: string;
    description: string | null;
    resourceId: string;
  };
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsCreateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    resourceId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type AppsCreateResponse = AppsCreateResponses[keyof AppsCreateResponses];

export type AppsDeleteData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    resourceId: string;
  };
  url: "/apps/{appId}";
};

export type AppsDeleteResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type AppsDeleteResponse = AppsDeleteResponses[keyof AppsDeleteResponses];

export type AppsGetData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    resourceId: string;
  };
  url: "/apps/{appId}";
};

export type AppsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    resourceId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type AppsGetResponse = AppsGetResponses[keyof AppsGetResponses];

export type AppsUpdateData = {
  body: {
    name: string;
    description: string | null;
  };
  path: {
    appId: string;
  };
  query: {
    resourceId: string;
  };
  url: "/apps/{appId}";
};

export type AppsUpdateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    resourceId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type AppsUpdateResponse = AppsUpdateResponses[keyof AppsUpdateResponses];

export type AppsDeployData = {
  body: {
    deploymentId: string;
  };
  path: {
    appId: string;
  };
  query: {
    resourceId: string;
  };
  url: "/apps/{appId}/deploy";
};

export type AppsDeployResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    projectId: string;
    resourceId: string;
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type AppsDeployResponse = AppsDeployResponses[keyof AppsDeployResponses];

export type DeploymentsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    appId: string;
    resourceId: string;
  };
  url: "/deployments";
};

export type DeploymentsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type DeploymentsListResponse = DeploymentsListResponses[keyof DeploymentsListResponses];

export type DeploymentsCreateData = {
  body: {
    appId: string;
    assets: [
      {
        contentType: "application/javascript";
        encoding: "utf-8";
        checksum: string;
        contentLength: number;
        objectKey: string;
      },
    ];
    resourceId: string;
  };
  path?: never;
  query?: never;
  url: "/deployments";
};

export type DeploymentsCreateResponses = {
  /**
   * OK
   */
  200: {
    assets: [
      {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "application/javascript";
          encoding: "utf-8";
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl: string;
      },
    ];
    deployment: {
      id: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      createdAt: string;
      updatedAt: string;
    };
  };
};

export type DeploymentsCreateResponse =
  DeploymentsCreateResponses[keyof DeploymentsCreateResponses];

export type DeploymentsGetData = {
  body?: never;
  path: {
    deploymentId: string;
  };
  query: {
    resourceId: string;
  };
  url: "/deployments/{deploymentId}";
};

export type DeploymentsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsGetResponse = DeploymentsGetResponses[keyof DeploymentsGetResponses];

export type DeploymentsPublishData = {
  body: {
    resourceId: string;
    rollout?: boolean;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/deployments/{deploymentId}";
};

export type DeploymentsPublishResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsPublishResponse =
  DeploymentsPublishResponses[keyof DeploymentsPublishResponses];
