name: tailorkit

services:
  postgres:
    image: postgres
    container_name: tailorkit-postgres
    environment:
      POSTGRES_DB: tailorkit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - tailorkit_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  email:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025" # SMTP port
      - "4000:8025" # Web UI
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8025/livez"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tailorkit_postgres_data:
