name: tailorkit

services:
  postgres:
    image: postgres:18
    container_name: tailorkit-postgres
    environment:
      POSTGRES_DB: tailorkit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdb_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  email:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025" # SMTP port
      - "4000:8025" # Web UI
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8025/livez"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: chrislusf/seaweedfs:latest
    container_name: tailorkit-s3
    ports:
      - "8333:8333" # S3-compatible API
      - "9333:9333" # Master API
      - "4010:8888" # Filer UI
    volumes:
      - seaweedfs_data:/data
    command: >
      server
      -s3
      -dir=/data
    restart: unless-stopped

  s3-init:
    image: amazon/aws-cli:latest
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      aws configure set aws_access_key_id some_access_key;
      aws configure set aws_secret_access_key some_secret_key;
      aws configure set default.region us-east-1;
      aws --endpoint-url=http://s3:8333 s3 mb s3://tailorkit || true;
      "

volumes:
  pgdb_data:
  seaweedfs_data:
