name: tailorkit

services:
  postgres:
    image: postgres:18
    container_name: tailorkit-postgres
    environment:
      POSTGRES_DB: tailorkit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  email:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025" # SMTP port
      - "4000:8025" # Web UI
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8025/livez"]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs-perms:
    image: alpine:3.22
    user: root
    volumes:
      - rustfs_data:/data
    command: chown -R 10001:10001 /data

  rustfs:
    image: rustfs/rustfs:latest
    container_name: tailorkit-rustfs
    depends_on:
      rustfs-perms:
        condition: service_completed_successfully
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: "true"
    ports:
      - "9000:9000" # S3-compatible API
      - "9001:9001" # Console
    volumes:
      - rustfs_data:/data
    command: /data
    restart: unless-stopped

  rustfs-create-bucket:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      - rustfs
    entrypoint: >
      /bin/sh -c "
      until mc alias set rustfs http://rustfs:9000 rustfsadmin rustfsadmin; do sleep 2; done;
      mc mb --ignore-existing rustfs/tailorkit;
      "

volumes:
  pg_data:
  rustfs_data:
