/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as MyWeekRouteImport } from './routes/my-week'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ApiTailorkitSplatRouteImport } from './routes/api/tailorkit.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWeekRoute = MyWeekRouteImport.update({
  id: '/my-week',
  path: '/my-week',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailorkitSplatRoute = ApiTailorkitSplatRouteImport.update({
  id: '/api/tailorkit/$',
  path: '/api/tailorkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/follow-ups': typeof FollowUpsRoute
  '/my-week': typeof MyWeekRoute
  '/pipeline': typeof PipelineRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/follow-ups': typeof FollowUpsRoute
  '/my-week': typeof MyWeekRoute
  '/pipeline': typeof PipelineRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/follow-ups': typeof FollowUpsRoute
  '/my-week': typeof MyWeekRoute
  '/pipeline': typeof PipelineRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/follow-ups'
    | '/my-week'
    | '/pipeline'
    | '/api/tailorkit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/follow-ups'
    | '/my-week'
    | '/pipeline'
    | '/api/tailorkit/$'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/follow-ups'
    | '/my-week'
    | '/pipeline'
    | '/api/tailorkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  FollowUpsRoute: typeof FollowUpsRoute
  MyWeekRoute: typeof MyWeekRoute
  PipelineRoute: typeof PipelineRoute
  ApiTailorkitSplatRoute: typeof ApiTailorkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-week': {
      id: '/my-week'
      path: '/my-week'
      fullPath: '/my-week'
      preLoaderRoute: typeof MyWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailorkit/$': {
      id: '/api/tailorkit/$'
      path: '/api/tailorkit/$'
      fullPath: '/api/tailorkit/$'
      preLoaderRoute: typeof ApiTailorkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  FollowUpsRoute: FollowUpsRoute,
  MyWeekRoute: MyWeekRoute,
  PipelineRoute: PipelineRoute,
  ApiTailorkitSplatRoute: ApiTailorkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
