/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as ApiTailorkitSplatRouteImport } from './routes/api/tailorkit.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => DealsRoute,
} as any)
const ApiTailorkitSplatRoute = ApiTailorkitSplatRouteImport.update({
  id: '/api/tailorkit/$',
  path: '/api/tailorkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/api/auth': typeof ApiAuthRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/api/auth': typeof ApiAuthRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deals': typeof DealsRouteWithChildren
  '/api/auth': typeof ApiAuthRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/deals'
    | '/api/auth'
    | '/customers/$customerId'
    | '/deals/$dealId'
    | '/api/tailorkit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/deals'
    | '/api/auth'
    | '/customers/$customerId'
    | '/deals/$dealId'
    | '/api/tailorkit/$'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/deals'
    | '/api/auth'
    | '/customers/$customerId'
    | '/deals/$dealId'
    | '/api/tailorkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DealsRoute: typeof DealsRouteWithChildren
  ApiAuthRoute: typeof ApiAuthRoute
  ApiTailorkitSplatRoute: typeof ApiTailorkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof DealsRoute
    }
    '/api/tailorkit/$': {
      id: '/api/tailorkit/$'
      path: '/api/tailorkit/$'
      fullPath: '/api/tailorkit/$'
      preLoaderRoute: typeof ApiTailorkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface DealsRouteChildren {
  DealsDealIdRoute: typeof DealsDealIdRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsDealIdRoute: DealsDealIdRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DealsRoute: DealsRouteWithChildren,
  ApiAuthRoute: ApiAuthRoute,
  ApiTailorkitSplatRoute: ApiTailorkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
