/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as appOnboardingRouteImport } from './routes/(app)/onboarding'
import { Route as appOrgSlugRouteRouteImport } from './routes/(app)/$orgSlug/route'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as appAccountSettingsRouteRouteImport } from './routes/(app)/account/settings/route'
import { Route as appOrgSlugorgRouteRouteImport } from './routes/(app)/$orgSlug/(org)/route'
import { Route as appOrgSlugProjectSlugRouteRouteImport } from './routes/(app)/$orgSlug/$projectSlug/route'
import { Route as appAccountSettingsIndexRouteImport } from './routes/(app)/account/settings/index'
import { Route as appOrgSlugorgIndexRouteImport } from './routes/(app)/$orgSlug/(org)/index'
import { Route as appOrgSlugProjectSlugIndexRouteImport } from './routes/(app)/$orgSlug/$projectSlug/index'
import { Route as appAccountSettingsSecurityRouteImport } from './routes/(app)/account/settings/security'
import { Route as appOrgSlugorgSettingsRouteImport } from './routes/(app)/$orgSlug/(org)/settings'
import { Route as appOrgSlugorgProjectsRouteImport } from './routes/(app)/$orgSlug/(org)/projects'
import { Route as appOrgSlugorgSettingsIndexRouteImport } from './routes/(app)/$orgSlug/(org)/settings/index'
import { Route as appOrgSlugorgSettingsMembersRouteImport } from './routes/(app)/$orgSlug/(org)/settings/members'
import { Route as appOrgSlugorgSettingsBillingRouteImport } from './routes/(app)/$orgSlug/(org)/settings/billing'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const appOnboardingRoute = appOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrgSlugRouteRoute = appOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appAccountSettingsRouteRoute = appAccountSettingsRouteRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrgSlugorgRouteRoute = appOrgSlugorgRouteRouteImport.update({
  id: '/(org)',
  getParentRoute: () => appOrgSlugRouteRoute,
} as any)
const appOrgSlugProjectSlugRouteRoute =
  appOrgSlugProjectSlugRouteRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => appOrgSlugRouteRoute,
  } as any)
const appAccountSettingsIndexRoute = appAccountSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAccountSettingsRouteRoute,
} as any)
const appOrgSlugorgIndexRoute = appOrgSlugorgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appOrgSlugorgRouteRoute,
} as any)
const appOrgSlugProjectSlugIndexRoute =
  appOrgSlugProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appOrgSlugProjectSlugRouteRoute,
  } as any)
const appAccountSettingsSecurityRoute =
  appAccountSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appAccountSettingsRouteRoute,
  } as any)
const appOrgSlugorgSettingsRoute = appOrgSlugorgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appOrgSlugorgRouteRoute,
} as any)
const appOrgSlugorgProjectsRoute = appOrgSlugorgProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => appOrgSlugorgRouteRoute,
} as any)
const appOrgSlugorgSettingsIndexRoute =
  appOrgSlugorgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appOrgSlugorgSettingsRoute,
  } as any)
const appOrgSlugorgSettingsMembersRoute =
  appOrgSlugorgSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => appOrgSlugorgSettingsRoute,
  } as any)
const appOrgSlugorgSettingsBillingRoute =
  appOrgSlugorgSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => appOrgSlugorgSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/$orgSlug': typeof appOrgSlugorgRouteRouteWithChildren
  '/onboarding': typeof appOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/$orgSlug/$projectSlug': typeof appOrgSlugProjectSlugRouteRouteWithChildren
  '/account/settings': typeof appAccountSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/$orgSlug/projects': typeof appOrgSlugorgProjectsRoute
  '/$orgSlug/settings': typeof appOrgSlugorgSettingsRouteWithChildren
  '/account/settings/security': typeof appAccountSettingsSecurityRoute
  '/$orgSlug/$projectSlug/': typeof appOrgSlugProjectSlugIndexRoute
  '/$orgSlug/': typeof appOrgSlugorgIndexRoute
  '/account/settings/': typeof appAccountSettingsIndexRoute
  '/$orgSlug/settings/billing': typeof appOrgSlugorgSettingsBillingRoute
  '/$orgSlug/settings/members': typeof appOrgSlugorgSettingsMembersRoute
  '/$orgSlug/settings/': typeof appOrgSlugorgSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/$orgSlug': typeof appOrgSlugorgIndexRoute
  '/onboarding': typeof appOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/$orgSlug/projects': typeof appOrgSlugorgProjectsRoute
  '/account/settings/security': typeof appAccountSettingsSecurityRoute
  '/$orgSlug/$projectSlug': typeof appOrgSlugProjectSlugIndexRoute
  '/account/settings': typeof appAccountSettingsIndexRoute
  '/$orgSlug/settings/billing': typeof appOrgSlugorgSettingsBillingRoute
  '/$orgSlug/settings/members': typeof appOrgSlugorgSettingsMembersRoute
  '/$orgSlug/settings': typeof appOrgSlugorgSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/(app)/$orgSlug': typeof appOrgSlugRouteRouteWithChildren
  '/(app)/onboarding': typeof appOnboardingRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/$orgSlug/$projectSlug': typeof appOrgSlugProjectSlugRouteRouteWithChildren
  '/(app)/$orgSlug/(org)': typeof appOrgSlugorgRouteRouteWithChildren
  '/(app)/account/settings': typeof appAccountSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(app)/$orgSlug/(org)/projects': typeof appOrgSlugorgProjectsRoute
  '/(app)/$orgSlug/(org)/settings': typeof appOrgSlugorgSettingsRouteWithChildren
  '/(app)/account/settings/security': typeof appAccountSettingsSecurityRoute
  '/(app)/$orgSlug/$projectSlug/': typeof appOrgSlugProjectSlugIndexRoute
  '/(app)/$orgSlug/(org)/': typeof appOrgSlugorgIndexRoute
  '/(app)/account/settings/': typeof appAccountSettingsIndexRoute
  '/(app)/$orgSlug/(org)/settings/billing': typeof appOrgSlugorgSettingsBillingRoute
  '/(app)/$orgSlug/(org)/settings/members': typeof appOrgSlugorgSettingsMembersRoute
  '/(app)/$orgSlug/(org)/settings/': typeof appOrgSlugorgSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/$orgSlug'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/verify-email'
    | '/'
    | '/$orgSlug/$projectSlug'
    | '/account/settings'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/$orgSlug/projects'
    | '/$orgSlug/settings'
    | '/account/settings/security'
    | '/$orgSlug/$projectSlug/'
    | '/$orgSlug/'
    | '/account/settings/'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/$orgSlug'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/verify-email'
    | '/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/$orgSlug/projects'
    | '/account/settings/security'
    | '/$orgSlug/$projectSlug'
    | '/account/settings'
    | '/$orgSlug/settings/billing'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/logout'
    | '/(app)/$orgSlug'
    | '/(app)/onboarding'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(app)/'
    | '/(app)/$orgSlug/$projectSlug'
    | '/(app)/$orgSlug/(org)'
    | '/(app)/account/settings'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(app)/$orgSlug/(org)/projects'
    | '/(app)/$orgSlug/(org)/settings'
    | '/(app)/account/settings/security'
    | '/(app)/$orgSlug/$projectSlug/'
    | '/(app)/$orgSlug/(org)/'
    | '/(app)/account/settings/'
    | '/(app)/$orgSlug/(org)/settings/billing'
    | '/(app)/$orgSlug/(org)/settings/members'
    | '/(app)/$orgSlug/(org)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/onboarding': {
      id: '/(app)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof appOnboardingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/$orgSlug': {
      id: '/(app)/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof appOrgSlugRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/account/settings': {
      id: '/(app)/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof appAccountSettingsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/$orgSlug/(org)': {
      id: '/(app)/$orgSlug/(org)'
      path: ''
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof appOrgSlugorgRouteRouteImport
      parentRoute: typeof appOrgSlugRouteRoute
    }
    '/(app)/$orgSlug/$projectSlug': {
      id: '/(app)/$orgSlug/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$orgSlug/$projectSlug'
      preLoaderRoute: typeof appOrgSlugProjectSlugRouteRouteImport
      parentRoute: typeof appOrgSlugRouteRoute
    }
    '/(app)/account/settings/': {
      id: '/(app)/account/settings/'
      path: '/'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof appAccountSettingsIndexRouteImport
      parentRoute: typeof appAccountSettingsRouteRoute
    }
    '/(app)/$orgSlug/(org)/': {
      id: '/(app)/$orgSlug/(org)/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof appOrgSlugorgIndexRouteImport
      parentRoute: typeof appOrgSlugorgRouteRoute
    }
    '/(app)/$orgSlug/$projectSlug/': {
      id: '/(app)/$orgSlug/$projectSlug/'
      path: '/'
      fullPath: '/$orgSlug/$projectSlug/'
      preLoaderRoute: typeof appOrgSlugProjectSlugIndexRouteImport
      parentRoute: typeof appOrgSlugProjectSlugRouteRoute
    }
    '/(app)/account/settings/security': {
      id: '/(app)/account/settings/security'
      path: '/security'
      fullPath: '/account/settings/security'
      preLoaderRoute: typeof appAccountSettingsSecurityRouteImport
      parentRoute: typeof appAccountSettingsRouteRoute
    }
    '/(app)/$orgSlug/(org)/settings': {
      id: '/(app)/$orgSlug/(org)/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof appOrgSlugorgSettingsRouteImport
      parentRoute: typeof appOrgSlugorgRouteRoute
    }
    '/(app)/$orgSlug/(org)/projects': {
      id: '/(app)/$orgSlug/(org)/projects'
      path: '/projects'
      fullPath: '/$orgSlug/projects'
      preLoaderRoute: typeof appOrgSlugorgProjectsRouteImport
      parentRoute: typeof appOrgSlugorgRouteRoute
    }
    '/(app)/$orgSlug/(org)/settings/': {
      id: '/(app)/$orgSlug/(org)/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof appOrgSlugorgSettingsIndexRouteImport
      parentRoute: typeof appOrgSlugorgSettingsRoute
    }
    '/(app)/$orgSlug/(org)/settings/members': {
      id: '/(app)/$orgSlug/(org)/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof appOrgSlugorgSettingsMembersRouteImport
      parentRoute: typeof appOrgSlugorgSettingsRoute
    }
    '/(app)/$orgSlug/(org)/settings/billing': {
      id: '/(app)/$orgSlug/(org)/settings/billing'
      path: '/billing'
      fullPath: '/$orgSlug/settings/billing'
      preLoaderRoute: typeof appOrgSlugorgSettingsBillingRouteImport
      parentRoute: typeof appOrgSlugorgSettingsRoute
    }
  }
}

interface appOrgSlugProjectSlugRouteRouteChildren {
  appOrgSlugProjectSlugIndexRoute: typeof appOrgSlugProjectSlugIndexRoute
}

const appOrgSlugProjectSlugRouteRouteChildren: appOrgSlugProjectSlugRouteRouteChildren =
  {
    appOrgSlugProjectSlugIndexRoute: appOrgSlugProjectSlugIndexRoute,
  }

const appOrgSlugProjectSlugRouteRouteWithChildren =
  appOrgSlugProjectSlugRouteRoute._addFileChildren(
    appOrgSlugProjectSlugRouteRouteChildren,
  )

interface appOrgSlugorgSettingsRouteChildren {
  appOrgSlugorgSettingsBillingRoute: typeof appOrgSlugorgSettingsBillingRoute
  appOrgSlugorgSettingsMembersRoute: typeof appOrgSlugorgSettingsMembersRoute
  appOrgSlugorgSettingsIndexRoute: typeof appOrgSlugorgSettingsIndexRoute
}

const appOrgSlugorgSettingsRouteChildren: appOrgSlugorgSettingsRouteChildren = {
  appOrgSlugorgSettingsBillingRoute: appOrgSlugorgSettingsBillingRoute,
  appOrgSlugorgSettingsMembersRoute: appOrgSlugorgSettingsMembersRoute,
  appOrgSlugorgSettingsIndexRoute: appOrgSlugorgSettingsIndexRoute,
}

const appOrgSlugorgSettingsRouteWithChildren =
  appOrgSlugorgSettingsRoute._addFileChildren(
    appOrgSlugorgSettingsRouteChildren,
  )

interface appOrgSlugorgRouteRouteChildren {
  appOrgSlugorgProjectsRoute: typeof appOrgSlugorgProjectsRoute
  appOrgSlugorgSettingsRoute: typeof appOrgSlugorgSettingsRouteWithChildren
  appOrgSlugorgIndexRoute: typeof appOrgSlugorgIndexRoute
}

const appOrgSlugorgRouteRouteChildren: appOrgSlugorgRouteRouteChildren = {
  appOrgSlugorgProjectsRoute: appOrgSlugorgProjectsRoute,
  appOrgSlugorgSettingsRoute: appOrgSlugorgSettingsRouteWithChildren,
  appOrgSlugorgIndexRoute: appOrgSlugorgIndexRoute,
}

const appOrgSlugorgRouteRouteWithChildren =
  appOrgSlugorgRouteRoute._addFileChildren(appOrgSlugorgRouteRouteChildren)

interface appOrgSlugRouteRouteChildren {
  appOrgSlugProjectSlugRouteRoute: typeof appOrgSlugProjectSlugRouteRouteWithChildren
  appOrgSlugorgRouteRoute: typeof appOrgSlugorgRouteRouteWithChildren
}

const appOrgSlugRouteRouteChildren: appOrgSlugRouteRouteChildren = {
  appOrgSlugProjectSlugRouteRoute: appOrgSlugProjectSlugRouteRouteWithChildren,
  appOrgSlugorgRouteRoute: appOrgSlugorgRouteRouteWithChildren,
}

const appOrgSlugRouteRouteWithChildren = appOrgSlugRouteRoute._addFileChildren(
  appOrgSlugRouteRouteChildren,
)

interface appAccountSettingsRouteRouteChildren {
  appAccountSettingsSecurityRoute: typeof appAccountSettingsSecurityRoute
  appAccountSettingsIndexRoute: typeof appAccountSettingsIndexRoute
}

const appAccountSettingsRouteRouteChildren: appAccountSettingsRouteRouteChildren =
  {
    appAccountSettingsSecurityRoute: appAccountSettingsSecurityRoute,
    appAccountSettingsIndexRoute: appAccountSettingsIndexRoute,
  }

const appAccountSettingsRouteRouteWithChildren =
  appAccountSettingsRouteRoute._addFileChildren(
    appAccountSettingsRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appOrgSlugRouteRoute: typeof appOrgSlugRouteRouteWithChildren
  appOnboardingRoute: typeof appOnboardingRoute
  appIndexRoute: typeof appIndexRoute
  appAccountSettingsRouteRoute: typeof appAccountSettingsRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appOrgSlugRouteRoute: appOrgSlugRouteRouteWithChildren,
  appOnboardingRoute: appOnboardingRoute,
  appIndexRoute: appIndexRoute,
  appAccountSettingsRouteRoute: appAccountSettingsRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
