import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadSchemaFromModule } from "../schema";

interface JsonSchema {
  additionalProperties?: boolean | JsonSchema;
  anyOf?: JsonSchema[];
  enum?: unknown[];
  items?: JsonSchema;
  not?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  type?: string | string[];
}

interface SerializedCallback {
  input?: JsonSchema[];
  output?: JsonSchema;
}

interface SerializedComponent {
  callbacks?: Record<string, SerializedCallback>;
  fieldKeys?: string[];
  fields?: JsonSchema;
  slots?: string[];
}

interface SerializedScreen {
  context?: JsonSchema;
}

interface SerializedActions {
  [key: string]: SerializedAction | SerializedActions;
}

interface SerializedAction {
  input?: JsonSchema;
  output?: JsonSchema;
}

interface TailorKitSchemaFile {
  actions?: SerializedActions;
  components?: Record<string, SerializedComponent>;
  screens?: Record<string, SerializedScreen>;
}

export interface GenerateTypesOptions {
  cwd?: string;
  outFile?: string;
  schemaFile?: string;
  experimentalSchemaFile?: string;
}

const generatedHeader = `/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";
`;

const fallbackObjectType = "Record<string, never>";

const quote = (value: string): string => JSON.stringify(value);

const toPropertyKey = (value: string): string => {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value)) {
    return value;
  }

  return quote(value);
};

const toLiteralType = (value: unknown): string => {
  if (typeof value === "string") {
    return quote(value);
  }
  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return JSON.stringify(value);
  }

  return "unknown";
};

const toTypeScriptType = (schema: JsonSchema | undefined, depth = 0): string => {
  if (schema === undefined) {
    return "unknown";
  }

  if (isNeverSchema(schema)) {
    return "never";
  }

  if (schema.enum !== undefined && schema.enum.length > 0) {
    return schema.enum.map(toLiteralType).join(" | ");
  }

  if (schema.anyOf !== undefined && schema.anyOf.length > 0) {
    const options = schema.anyOf
      .filter((option) => !isNeverSchema(option))
      .map((option) => toTypeScriptType(option, depth))
      .filter((option) => option !== "never");

    if (options.length === 0) {
      return "never";
    }

    const uniqueOptions = [...new Set(options)];
    return uniqueOptions.join(" | ");
  }

  const schemaType = Array.isArray(schema.type) ? schema.type[0] : schema.type;

  if (schemaType === "string") {
    return "string";
  }
  if (schemaType === "number" || schemaType === "integer") {
    return "number";
  }
  if (schemaType === "boolean") {
    return "boolean";
  }
  if (schemaType === "array") {
    return `${toTypeScriptType(schema.items, depth)}[]`;
  }
  if (schemaType === "object") {
    return toObjectType(schema, depth);
  }

  return "unknown";
};

const isNeverSchema = (schema: JsonSchema): boolean =>
  schema.not !== undefined && Object.keys(schema.not).length === 0;

const isNeverOnlyObject = (schema: JsonSchema): boolean => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.values(properties);

  return (
    (Array.isArray(schema.type) ? schema.type.includes("object") : schema.type === "object") &&
    propertyEntries.length > 0 &&
    propertyEntries.every(isNeverSchema)
  );
};

const toObjectType = (schema: JsonSchema, depth: number): string => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.entries(properties);

  if (isNeverOnlyObject(schema)) {
    return "never";
  }

  if (propertyEntries.length === 0) {
    return fallbackObjectType;
  }

  const required = new Set(schema.required);
  const currentIndent = " ".repeat(depth);
  const propertyIndent = " ".repeat(depth + 2);
  const lines = ["{"];

  for (const [key, propertySchema] of propertyEntries) {
    const optional = required.has(key) ? "" : "?";
    lines.push(
      `${propertyIndent}${toPropertyKey(key)}${optional}: ${toTypeScriptType(propertySchema, depth + 2)};`,
    );
  }

  lines.push(`${currentIndent}}`);
  return lines.join("\n");
};

const toIdentifier = (name: string): string => {
  const identifier = name.replaceAll(/[^A-Za-z0-9_$]/gu, "_");

  if (/^[A-Za-z_$]/u.test(identifier)) {
    return identifier;
  }

  return `_${identifier}`;
};

const toPropsName = (componentName: string): string => `${toIdentifier(componentName)}Props`;

const toTypeName = (name: string): string => {
  const identifier = toIdentifier(name);
  return `${identifier.charAt(0).toUpperCase()}${identifier.slice(1)}`;
};

const getComponentFields = (component: SerializedComponent): Record<string, JsonSchema> => {
  if (component.fields?.properties !== undefined) {
    return component.fields.properties;
  }

  const fields: Record<string, JsonSchema> = {};

  for (const key of component.fieldKeys ?? []) {
    fields[key] = {};
  }

  return fields;
};

const renderResponsiveType = (
  schema: JsonSchema | undefined,
  depth: number,
): string | undefined => {
  if (schema?.anyOf === undefined || schema.anyOf.length !== 2) {
    return undefined;
  }

  const [firstOption, secondOption] = schema.anyOf.filter((option) => !isNeverSchema(option));
  if (firstOption === undefined || secondOption === undefined) {
    return undefined;
  }

  let scalarOption: JsonSchema | undefined;
  let responsiveOption: JsonSchema | undefined;

  if (firstOption.type === "object") {
    scalarOption = secondOption;
    responsiveOption = firstOption;
  } else if (secondOption.type === "object") {
    scalarOption = firstOption;
    responsiveOption = secondOption;
  }

  if (scalarOption === undefined || responsiveOption === undefined) {
    return undefined;
  }

  const scalarType = toTypeScriptType(scalarOption, depth);
  if (scalarType === "never") {
    return "never";
  }

  const properties = Object.values(responsiveOption.properties ?? {});
  if (properties.length === 0) {
    return undefined;
  }

  const responsiveTypes = properties.map((property) => toTypeScriptType(property, depth));
  if (responsiveTypes.some((type) => type !== scalarType && type !== "never")) {
    return undefined;
  }

  return `Responsive<${scalarType}>`;
};

const renderFieldType = (schema: JsonSchema | undefined, depth: number): string =>
  renderResponsiveType(schema, depth) ?? toTypeScriptType(schema, depth);

const collectFieldTypeAliases = (
  components: Record<string, SerializedComponent>,
): Record<string, string> => {
  const aliases: Record<string, string> = {};
  const seenByAlias = new Map<string, string>();
  const conflictedAliases = new Set<string>();

  for (const component of Object.values(components)) {
    for (const [key, schema] of Object.entries(getComponentFields(component))) {
      const alias = toTypeName(key);
      const type = renderFieldType(schema, 0);
      const seenType = seenByAlias.get(alias);

      if (seenType === undefined) {
        seenByAlias.set(alias, type);
        aliases[key] = alias;
        continue;
      }

      if (seenType !== type) {
        conflictedAliases.add(alias);
      }
    }
  }

  return Object.fromEntries(
    Object.entries(aliases).filter(([, alias]) => !conflictedAliases.has(alias)),
  );
};

const renderTypeAliases = (
  components: Record<string, SerializedComponent>,
  aliases: Record<string, string>,
): string => {
  const lines = [
    'export type Breakpoint = "base" | "sm" | "md" | "lg" | "xl" | "2xl";',
    "export type Responsive<TValue> = TValue | Partial<Record<Breakpoint, TValue>>;",
  ];
  const emitted = new Set<string>();

  for (const component of Object.values(components)) {
    for (const [key, schema] of Object.entries(getComponentFields(component))) {
      const alias = aliases[key];
      if (alias === undefined || emitted.has(alias)) {
        continue;
      }

      emitted.add(alias);
      lines.push(`export type ${alias} = ${renderFieldType(schema, 0)};`);
    }
  }

  return lines.join("\n");
};

const renderScreenProps = (screens: Record<string, SerializedScreen>): string => {
  const lines = ["export interface ScreenPropsByPath {"];

  for (const [screenPath, screen] of Object.entries(screens)) {
    const context = toTypeScriptType(screen.context, 4);
    const contextLines = context.split("\n");
    lines.push(`  ${quote(screenPath)}: {`);
    lines.push(`    context: ${contextLines[0]}`);
    for (const line of contextLines.slice(1, -1)) {
      lines.push(line);
    }
    const lastContextLine = contextLines.at(-1);
    if (lastContextLine !== undefined && contextLines.length > 1) {
      lines.push(`${lastContextLine};`);
    } else {
      lines[lines.length - 1] = `${lines.at(-1)};`;
    }
    lines.push("  };");
  }

  lines.push("}");
  return lines.join("\n");
};

const renderComponent = (
  name: string,
  component: SerializedComponent,
  fieldAliases: Record<string, string>,
): string => {
  const propsName = toPropsName(name);
  const fields = getComponentFields(component);
  const callbacks = component.callbacks ?? {};
  const slots = component.slots ?? [];
  const lines = [`export interface ${propsName} {`];

  for (const [key, schema] of Object.entries(fields)) {
    lines.push(`  ${toPropertyKey(key)}?: ${fieldAliases[key] ?? renderFieldType(schema, 2)};`);
  }

  for (const [key, callback] of Object.entries(callbacks)) {
    const parameters = (callback.input ?? [])
      .map((schema, index) => `value${index + 1}: ${toTypeScriptType(schema, 2)}`)
      .join(", ");
    lines.push(`  ${toPropertyKey(key)}?: (${parameters}) => void;`);
  }

  lines.push("}");
  lines.push("");

  const slotsType = `readonly [${slots.map(quote).join(", ")}]`;
  const slotsValue = `[${slots.map(quote).join(", ")}] as const`;
  const callbackEntries = Object.entries(callbacks).map(
    ([key, callback]) => `${quote(key)}: ${callback.input?.length ?? 0}`,
  );
  const callbackOptions =
    callbackEntries.length > 0 ? `,\n  callbacks: { ${callbackEntries.join(", ")} }` : "";

  lines.push(
    `export const ${toIdentifier(name)} = /* @__PURE__ */ createRemoteComponent<${propsName}, ${slotsType}>(${quote(name)}, {`,
  );
  lines.push(`  slots: ${slotsValue}${callbackOptions},`);
  lines.push("});");

  return lines.join("\n");
};

const isSerializedAction = (
  value: SerializedAction | SerializedActions,
): value is SerializedAction => "input" in value || "output" in value;

const renderActions = (actions: SerializedActions, depth = 0): string => {
  const indent = " ".repeat(depth);
  const propertyIndent = " ".repeat(depth + 2);
  const lines = ["{"];

  for (const [key, value] of Object.entries(actions)) {
    if (isSerializedAction(value)) {
      const input = toTypeScriptType(value.input, depth + 2);
      const output = toTypeScriptType(value.output, depth + 2);
      lines.push(
        `${propertyIndent}${toPropertyKey(key)}: (input: ${input}) => Promise<${output}>;`,
      );
    } else {
      const nested = renderActions(value, depth + 2).split("\n");
      lines.push(`${propertyIndent}${toPropertyKey(key)}: ${nested[0]}`);
      lines.push(...nested.slice(1, -1));
      lines.push(`${nested.at(-1)};`);
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
};

const renderActionRuntime = (actions: SerializedActions, pathParts: string[] = []): string => {
  const lines = ["{"];

  for (const [key, value] of Object.entries(actions)) {
    const path = [...pathParts, key];
    if (isSerializedAction(value)) {
      lines.push(`  ${toPropertyKey(key)}: async (input: unknown) => {`);
      lines.push(
        `    const response = await fetch(${quote(`/api/tailorkit/actions/${path.join(".")}`)}, {`,
      );
      lines.push(`      body: JSON.stringify(input),`);
      lines.push(`      headers: { "content-type": "application/json" },`);
      lines.push(`      method: "POST",`);
      lines.push(`    });`);
      lines.push(`    if (!response.ok) throw new Error(await response.text());`);
      lines.push(`    return response.json();`);
      lines.push(`  },`);
    } else {
      const nested = renderActionRuntime(value, path).split("\n");
      lines.push(`  ${toPropertyKey(key)}: ${nested[0]}`);
      lines.push(...nested.slice(1).map((line) => `  ${line}`));
      lines.push(",");
    }
  }

  lines.push("}");
  return lines.join("\n");
};

export const renderGeneratedTypes = (schema: TailorKitSchemaFile): string => {
  const actionsType = renderActions(schema.actions ?? {});
  const components = schema.components ?? {};
  const fieldAliases = collectFieldTypeAliases(components);
  const chunks = [
    generatedHeader,
    renderScreenProps(schema.screens ?? {}),
    `declare module "@tailorkit/app" {
  interface TailorKitScreens extends ScreenPropsByPath {}
}

export type ScreenPath = keyof ScreenPropsByPath & string;
export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];
export type TailorKitActions = ${actionsType};
export const actions = ${renderActionRuntime(schema.actions ?? {})} as TailorKitActions;`,
    renderTypeAliases(components, fieldAliases),
  ];

  for (const [name, component] of Object.entries(components)) {
    chunks.push(renderComponent(name, component, fieldAliases));
  }

  return `${chunks.join("\n\n")}\n`;
};

export const generateTypes = async (options: GenerateTypesOptions = {}): Promise<string> => {
  const root = path.resolve(options.cwd ?? ".");
  const outPath = path.resolve(root, options.outFile ?? path.join("src", "tailorkit.gen.ts"));

  let schema: TailorKitSchemaFile;
  if (options.experimentalSchemaFile) {
    schema = (await loadSchemaFromModule({
      cwd: root,
      filePath: options.experimentalSchemaFile,
    })) as TailorKitSchemaFile;
  } else {
    const schemaPath = path.resolve(root, options.schemaFile ?? "tailorkit.schema.json");
    schema = JSON.parse(await readFile(schemaPath, "utf-8")) as TailorKitSchemaFile;
  }

  const output = renderGeneratedTypes(schema);

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, output, "utf-8");

  return outPath;
};
