import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { loadSchemaFromModule } from "../schema";

interface JsonSchema {
  additionalProperties?: boolean | JsonSchema;
  anyOf?: JsonSchema[];
  enum?: unknown[];
  items?: JsonSchema;
  not?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  type?: string | string[];
}

interface SerializedCallback {
  input?: JsonSchema[];
  output?: JsonSchema;
}

interface SerializedComponent {
  callbacks?: Record<string, SerializedCallback>;
  fieldKeys?: string[];
  fields?: JsonSchema;
  slots?: string[];
}

interface SerializedScreen {
  context?: JsonSchema;
}

interface TailorKitSchemaFile {
  components?: Record<string, SerializedComponent>;
  screens?: Record<string, SerializedScreen>;
}

export interface GenerateTypesOptions {
  cwd?: string;
  outFile?: string;
  schemaFile?: string;
  experimentalSchemaFile?: string;
}

const generatedHeader = `/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";
`;

const fallbackObjectType = "Record<string, never>";

const quote = (value: string): string => JSON.stringify(value);

const toPropertyKey = (value: string): string => {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value)) {
    return value;
  }

  return quote(value);
};

const toLiteralType = (value: unknown): string => {
  if (typeof value === "string") {
    return quote(value);
  }
  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return JSON.stringify(value);
  }

  return "unknown";
};

const toTypeScriptType = (schema: JsonSchema | undefined, depth = 0): string => {
  if (schema === undefined) {
    return "unknown";
  }

  if (isNeverSchema(schema)) {
    return "never";
  }

  if (schema.enum !== undefined && schema.enum.length > 0) {
    return schema.enum.map(toLiteralType).join(" | ");
  }

  if (schema.anyOf !== undefined && schema.anyOf.length > 0) {
    const options = schema.anyOf
      .filter((option) => !isNeverSchema(option))
      .map((option) => toTypeScriptType(option, depth))
      .filter((option) => option !== "never");

    if (options.length === 0) {
      return "never";
    }

    const uniqueOptions = [...new Set(options)];
    return uniqueOptions.join(" | ");
  }

  const schemaType = Array.isArray(schema.type) ? schema.type[0] : schema.type;

  if (schemaType === "string") {
    return "string";
  }
  if (schemaType === "number" || schemaType === "integer") {
    return "number";
  }
  if (schemaType === "boolean") {
    return "boolean";
  }
  if (schemaType === "array") {
    return `${toTypeScriptType(schema.items, depth)}[]`;
  }
  if (schemaType === "object") {
    return toObjectType(schema, depth);
  }

  return "unknown";
};

const isNeverSchema = (schema: JsonSchema): boolean =>
  schema.not !== undefined && Object.keys(schema.not).length === 0;

const isNeverOnlyObject = (schema: JsonSchema): boolean => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.values(properties);

  return (
    (Array.isArray(schema.type) ? schema.type.includes("object") : schema.type === "object") &&
    propertyEntries.length > 0 &&
    propertyEntries.every(isNeverSchema)
  );
};

const toObjectType = (schema: JsonSchema, depth: number): string => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.entries(properties);

  if (isNeverOnlyObject(schema)) {
    return "never";
  }

  if (propertyEntries.length === 0) {
    return fallbackObjectType;
  }

  const required = new Set(schema.required);
  const currentIndent = " ".repeat(depth);
  const propertyIndent = " ".repeat(depth + 2);
  const lines = ["{"];

  for (const [key, propertySchema] of propertyEntries) {
    const optional = required.has(key) ? "" : "?";
    lines.push(
      `${propertyIndent}${toPropertyKey(key)}${optional}: ${toTypeScriptType(propertySchema, depth + 2)};`,
    );
  }

  lines.push(`${currentIndent}}`);
  return lines.join("\n");
};

const toIdentifier = (name: string): string => {
  const identifier = name.replaceAll(/[^A-Za-z0-9_$]/gu, "_");

  if (/^[A-Za-z_$]/u.test(identifier)) {
    return identifier;
  }

  return `_${identifier}`;
};

const toPropsName = (componentName: string): string => `${toIdentifier(componentName)}Props`;

const getComponentFields = (component: SerializedComponent): Record<string, JsonSchema> => {
  if (component.fields?.properties !== undefined) {
    return component.fields.properties;
  }

  const fields: Record<string, JsonSchema> = {};

  for (const key of component.fieldKeys ?? []) {
    fields[key] = {};
  }

  return fields;
};

const renderScreenProps = (screens: Record<string, SerializedScreen>): string => {
  const lines = ["export interface ScreenPropsByPath {"];

  for (const [screenPath, screen] of Object.entries(screens)) {
    const context = toTypeScriptType(screen.context, 4);
    const contextLines = context.split("\n");
    lines.push(`  ${quote(screenPath)}: {`);
    lines.push(`    context: ${contextLines[0]}`);
    for (const line of contextLines.slice(1, -1)) {
      lines.push(line);
    }
    const lastContextLine = contextLines.at(-1);
    if (lastContextLine !== undefined && contextLines.length > 1) {
      lines.push(`${lastContextLine};`);
    } else {
      lines[lines.length - 1] = `${lines.at(-1)};`;
    }
    lines.push("  };");
  }

  lines.push("}");
  return lines.join("\n");
};

const renderComponent = (name: string, component: SerializedComponent): string => {
  const propsName = toPropsName(name);
  const fields = getComponentFields(component);
  const callbacks = component.callbacks ?? {};
  const slots = component.slots ?? [];
  const lines = [`export interface ${propsName} {`];

  for (const [key, schema] of Object.entries(fields)) {
    lines.push(`  ${toPropertyKey(key)}?: ${toTypeScriptType(schema, 2)};`);
  }

  for (const [key, callback] of Object.entries(callbacks)) {
    const parameters = (callback.input ?? [])
      .map((schema, index) => `value${index + 1}: ${toTypeScriptType(schema, 2)}`)
      .join(", ");
    lines.push(`  ${toPropertyKey(key)}?: (${parameters}) => void;`);
  }

  lines.push("}");
  lines.push("");

  const slotsType = `readonly [${slots.map(quote).join(", ")}]`;
  const slotsValue = `[${slots.map(quote).join(", ")}] as const`;
  const callbackEntries = Object.entries(callbacks).map(
    ([key, callback]) => `${quote(key)}: ${callback.input?.length ?? 0}`,
  );
  const callbackOptions =
    callbackEntries.length > 0 ? `,\n  callbacks: { ${callbackEntries.join(", ")} }` : "";

  lines.push(
    `export const ${toIdentifier(name)} = createRemoteComponent<${propsName}, ${slotsType}>(${quote(name)}, {`,
  );
  lines.push(`  slots: ${slotsValue}${callbackOptions},`);
  lines.push("});");

  return lines.join("\n");
};

export const renderGeneratedTypes = (schema: TailorKitSchemaFile): string => {
  const chunks = [
    generatedHeader,
    renderScreenProps(schema.screens ?? {}),
    `declare module "@tailorkit/app" {
  interface TailorKitScreens extends ScreenPropsByPath {}
}

export type ScreenPath = keyof ScreenPropsByPath & string;
export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];`,
  ];

  for (const [name, component] of Object.entries(schema.components ?? {})) {
    chunks.push(renderComponent(name, component));
  }

  return `${chunks.join("\n\n")}\n`;
};

export const generateTypes = async (options: GenerateTypesOptions = {}): Promise<string> => {
  const root = path.resolve(options.cwd ?? ".");
  const outPath = path.resolve(root, options.outFile ?? path.join("src", "tailorkit.gen.ts"));

  let schema: TailorKitSchemaFile;
  if (options.experimentalSchemaFile) {
    schema = (await loadSchemaFromModule({
      cwd: root,
      filePath: options.experimentalSchemaFile,
    })) as TailorKitSchemaFile;
  } else {
    const schemaPath = path.resolve(root, options.schemaFile ?? "tailorkit.schema.json");
    schema = JSON.parse(await readFile(schemaPath, "utf-8")) as TailorKitSchemaFile;
  }

  const output = renderGeneratedTypes(schema);

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, output, "utf-8");

  return outPath;
};
