import {
  attr,
  booleanOrString,
  createSchema,
  formSubmitterAttrs,
  INPUT_TYPE_VALUES,
  numberOrString,
} from "./globals";

export const inputSchema = createSchema<HTMLInputElement>("input", {
  accept: attr.string,
  alt: attr.string,
  autoComplete: attr.string,
  capture: booleanOrString,
  checked: attr.boolean,
  dirname: attr.string,
  disabled: attr.boolean,
  ...formSubmitterAttrs,
  height: numberOrString,
  list: attr.string,
  max: numberOrString,
  maxLength: attr.number,
  min: numberOrString,
  minLength: attr.number,
  multiple: attr.boolean,
  name: attr.string,
  pattern: attr.string,
  placeholder: attr.string,
  readOnly: attr.boolean,
  required: attr.boolean,
  size: attr.number,
  src: attr.string,
  step: numberOrString,
  type: attr.enum(...INPUT_TYPE_VALUES),
  value: numberOrString,
  width: numberOrString,
});
