import path from "node:path";
import { mkdir } from "node:fs/promises";
import { z } from "zod";

import type { LoadedTailorKitConfig } from "./config";

const typeReferenceSchema = z.string().regex(/^[^\n\r;]+$/u, {
  message: "Type references must be a single TypeScript type expression.",
});

const propNameSchema = z.string().regex(/^[A-Za-z_$][A-Za-z0-9_$]*\??$/u, {
  message: "Prop names must be TypeScript identifiers.",
});

const componentDefinitionSchema = z.object({
  props: z.record(propNameSchema, typeReferenceSchema).default({}),
});

const componentSpecSchema = z.object({
  components: z.record(z.string().regex(/^[A-Z][A-Za-z0-9_]*$/u), componentDefinitionSchema),
});

type ComponentSpec = z.infer<typeof componentSpecSchema>;

const generatedHeader = `/* eslint-disable */
// This file is generated by TailorKit. Do not edit it by hand.

import { createRemoteComponent } from "@tailorkit/sandbox-ui/worker";
import type { ComponentChildren, FunctionalComponent } from "preact";

`;

const toOptionalProperty = (name: string): string => {
  if (name.endsWith("?")) {
    return `${name}:`;
  }

  return `${name}?:`;
};

const generateComponentTypes = (spec: ComponentSpec): string => {
  const lines = [generatedHeader.trimEnd(), ""];

  for (const [name, definition] of Object.entries(spec.components)) {
    lines.push(`export interface ${name}Props {`);

    if (definition.props.children === undefined && definition.props["children?"] === undefined) {
      lines.push("  children?: ComponentChildren;");
    }

    for (const [propName, typeReference] of Object.entries(definition.props)) {
      lines.push(`  ${toOptionalProperty(propName)} ${typeReference};`);
    }

    lines.push("}");
    lines.push("");
    lines.push(
      `export const ${name} = createRemoteComponent("${name}") as unknown as FunctionalComponent<${name}Props>;`,
    );
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

export const generateTypes = async (loadedConfig: LoadedTailorKitConfig): Promise<string> => {
  const inputPath = path.resolve(loadedConfig.root, loadedConfig.config.components.input);
  const outputPath = path.resolve(loadedConfig.root, loadedConfig.config.components.output);
  const rawSpec = await Bun.file(inputPath).json();
  const spec = componentSpecSchema.parse(rawSpec);
  const generated = generateComponentTypes(spec);

  await mkdir(path.dirname(outputPath), { recursive: true });
  await Bun.write(outputPath, generated);

  return outputPath;
};
