interface TemplateOptions {
  formatting: boolean;
  linting: boolean;
  packageName: string;
  packageVersions: {
    oxfmt: string;
    oxlint: string;
    preact: string;
    typescript: string;
  };
  useWorkspaceDependencies?: boolean;
}

export const createPackageJson = ({
  formatting,
  linting,
  packageName,
  packageVersions,
  useWorkspaceDependencies,
}: TemplateOptions): string => {
  const tailorkitVersion = useWorkspaceDependencies ? "workspace:*" : "latest";
  const codeQualityScripts: Record<string, string> = {};
  const codeQualityDevDependencies: Record<string, string> = {};
  const checkScripts: string[] = [];
  const fixScripts: string[] = [];

  if (linting) {
    codeQualityScripts.lint = "oxlint";
    codeQualityScripts["lint:fix"] = "oxlint --fix";
    codeQualityDevDependencies.oxlint = packageVersions.oxlint;
    checkScripts.push("bun run lint");
    fixScripts.push("bun run lint:fix");
  }

  if (formatting) {
    codeQualityScripts.format = "oxfmt --check";
    codeQualityScripts["format:fix"] = "oxfmt --write";
    codeQualityDevDependencies.oxfmt = packageVersions.oxfmt;
    checkScripts.push("bun run format");
    fixScripts.push("bun run format:fix");
  }

  if (checkScripts.length > 0) {
    codeQualityScripts.check = checkScripts.join(" && ");
    codeQualityScripts.fix = fixScripts.join(" && ");
  }

  return `${JSON.stringify(
    {
      name: packageName,
      description: "A TailorKit.dev app that embeds in a host app to extend what it can do.",
      private: true,
      imports: {
        "#tailorkit": "./src/tailorkit.gen.ts",
      },
      scripts: {
        build: "tailorkit build",
        dev: "tailorkit dev",
        generate: "tailorkit generate",
        ...codeQualityScripts,
      },
      dependencies: {
        "@tailorkit/app": tailorkitVersion,
        preact: packageVersions.preact,
      },
      devDependencies: {
        "@tailorkit/cli": tailorkitVersion,
        ...codeQualityDevDependencies,
        typescript: packageVersions.typescript,
      },
      type: "module",
    },
    null,
    2,
  )}
`;
};

export const createTailorKitConfig =
  (): string => `import { defineTailorKitConfig } from "@tailorkit/app/config";

export default defineTailorKitConfig({
  client: {
    entry: "./src/client.ts",
  },
});
`;

export const createOxlintConfig = (): string => `import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: ["src/tailorkit.gen.ts"],
});
`;

export const createOxfmtConfig = (): string => `import { defineConfig } from "oxfmt";

export default defineConfig({
  ignorePatterns: ["src/tailorkit.gen.ts"],
});
`;

export const createComponentSpec = (): string => `${JSON.stringify(
  {
    version: 1,
    components: {
      Button: {
        callbacks: {
          onClick: {},
        },
        fieldKeys: ["disabled", "variant"],
        nativeEvents: {},
        slots: ["default"],
      },
      Card: {
        callbacks: {},
        fieldKeys: [],
        nativeEvents: {},
        slots: ["header", "content", "footer"],
      },
    },
    defaultContext: {
      additionalProperties: false,
      properties: {},
      type: "object",
    },
    screens: {},
  },
  null,
  2,
)}
`;

export const createFallbackScreen =
  (): string => `import type { DefaultScreenProps } from "#tailorkit";

const FallbackScreen = (_props: DefaultScreenProps) => <>Hello World from the fallback screen</>;

export default FallbackScreen;
`;

export const createClient = (): string => `import { defineClient } from "@tailorkit/app";
import FallbackScreen from "./views/fallback";

const client = defineClient({
  fallbackScreen: FallbackScreen,
});

export default client;
`;

export const createGeneratedFile = (): string => `/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";

export interface FallbackScreenProps {
  context: Record<string, never>;
}

export interface ScreenPropsByPath {
}

declare module "@tailorkit/app" {
  interface TailorKitFallbackScreenProps {
    context: Record<string, never>;
  }
  interface TailorKitScreens extends ScreenPropsByPath {}
}

export type DefaultScreenProps = FallbackScreenProps;
export type ScreenPath = keyof ScreenPropsByPath & string;
export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];

export interface ButtonProps {
  disabled?: unknown;
  variant?: unknown;
  onClick?: () => void;
}

export const Button = createRemoteComponent<ButtonProps, readonly ["default"]>("Button", {
  slots: ["default"] as const,
});

export interface CardProps {}

export const Card = createRemoteComponent<
  CardProps,
  readonly ["header", "content", "footer"]
>("Card", {
  slots: ["header", "content", "footer"] as const,
});
`;

export const createGitignore = (): string => `# TailorKit
.tailorkit

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Env
.env
.env.*
!.env.example

# Claude Code (local settings and session files)
.claude/settings.local.json
.claude/plans/
.claude/todos.json
.claude/worktrees
CLAUDE.local.md

# Editors
**/.idea
**/.#*
.nvmrc
`;

export const createTsconfig = (): string => `${JSON.stringify(
  {
    compilerOptions: {
      allowSyntheticDefaultImports: true,
      esModuleInterop: true,
      isolatedModules: true,
      jsx: "react-jsx",
      jsxImportSource: "preact",
      lib: ["ESNext", "DOM", "WebWorker"],
      module: "ESNext",
      moduleResolution: "bundler",
      noEmit: true,
      strict: true,
      target: "ESNext",
      types: ["@tailorkit/app/client"],
      verbatimModuleSyntax: true,
    },
    include: ["src", "tailorkit.config.ts"],
  },
  null,
  2,
)}
`;
