/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";

export interface FallbackScreenProps {
  context: Record<string, never>;
}

export interface ScreenPropsByPath {
}

declare module "@tailorkit/app" {
  interface TailorKitFallbackScreenProps {
    context: Record<string, never>;
  }
  interface TailorKitScreens extends ScreenPropsByPath {}
}

export type DefaultScreenProps = FallbackScreenProps;
export type ScreenPath = keyof ScreenPropsByPath & string;
export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];

export interface ButtonProps {
  disabled?: unknown;
  variant?: unknown;
  onClick?: () => void;
}

export const Button = createRemoteComponent<ButtonProps, readonly ["default"]>("Button", {
  slots: ["default"] as const,
});

export interface CardProps {}

export const Card = createRemoteComponent<
  CardProps,
  readonly ["header", "content", "footer"]
>("Card", {
  slots: ["header", "content", "footer"] as const,
});
