import path from "node:path";
import { mkdir } from "node:fs/promises";
import { TailorKitSchemaSpec } from "@tailorkit/spec";
import type { SerializedTailorKitSchema } from "@tailorkit/spec";
import { z } from "zod";

import type { LoadedTailorKitConfig } from "@tailorkit/app/config";

const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;

const componentNameSchema = z.string().regex(/^[A-Z][A-Za-z0-9_]*$/u, {
  message: "Component names must be PascalCase TypeScript identifiers.",
});

const slotNameSchema = z.string().regex(/^[A-Za-z_$][A-Za-z0-9_$]*$/u, {
  message: "Slot names must be TypeScript identifiers.",
});

const generatedHeader = `/* eslint-disable */

// This file was automatically generated by TailorKit.
// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "@tailorkit/app";
`;

type JsonSchema = Record<string, unknown>;

const validateComponentSpec = (spec: SerializedTailorKitSchema): void => {
  for (const [componentName, component] of Object.entries(spec.components)) {
    componentNameSchema.parse(componentName);

    for (const slot of component.slots) {
      slotNameSchema.parse(slot);
    }
  }
};

const formatPropertyName = (name: string): string =>
  identifierPattern.test(name) ? name : JSON.stringify(name);

const formatStringArray = (values: readonly string[]): string =>
  `[${values.map((value) => JSON.stringify(value)).join(", ")}] as const`;

const formatStringTupleType = (values: readonly string[]): string =>
  `readonly [${values.map((value) => JSON.stringify(value)).join(", ")}]`;

const formatLiteralType = (value: unknown): string => {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return String(value);
  }

  return "unknown";
};

const formatUnion = (values: readonly string[]): string => {
  const uniqueValues = [...new Set(values)];
  return uniqueValues.length === 0 ? "unknown" : uniqueValues.join(" | ");
};

const normalizeTypeNames = (type: unknown): string[] => {
  if (typeof type === "string") {
    return [type];
  }

  if (Array.isArray(type)) {
    return type.filter((value): value is string => typeof value === "string");
  }

  return [];
};

const formatObjectSchema = (schema: JsonSchema): string => {
  const properties =
    schema.properties && typeof schema.properties === "object"
      ? (schema.properties as Record<string, JsonSchema>)
      : {};
  const required = new Set(
    Array.isArray(schema.required)
      ? schema.required.filter((value): value is string => typeof value === "string")
      : [],
  );
  const entries = Object.entries(properties);

  if (entries.length === 0) {
    if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
      return `Record<string, ${jsonSchemaToType(schema.additionalProperties as JsonSchema)}>`;
    }

    if (schema.additionalProperties === false) {
      return "Record<string, never>";
    }

    return "Record<string, unknown>";
  }

  const propertyTypes = entries.map(([name, propertySchema]) => {
    const optional = required.has(name) ? "" : "?";
    return `${JSON.stringify(name)}${optional}: ${jsonSchemaToType(propertySchema)}`;
  });

  return `{ ${propertyTypes.join("; ")} }`;
};

const formatSchemaWithType = (schema: JsonSchema, typeName: string | undefined): string => {
  if (typeName === "string" || typeName === "number" || typeName === "boolean") {
    return typeName;
  }

  if (typeName === "integer") {
    return "number";
  }

  if (typeName === "null") {
    return "null";
  }

  if (typeName === "array") {
    const itemType =
      schema.items && typeof schema.items === "object"
        ? jsonSchemaToType(schema.items as JsonSchema)
        : "unknown";
    return `readonly ${itemType}[]`;
  }

  if (typeName === "object" || schema.properties !== undefined) {
    return formatObjectSchema(schema);
  }

  return "unknown";
};

const jsonSchemaToType = (schema: JsonSchema | undefined): string => {
  if (schema === undefined) {
    return "void";
  }

  if ("const" in schema) {
    return formatLiteralType(schema.const);
  }

  if (Array.isArray(schema.enum)) {
    return formatUnion(schema.enum.map(formatLiteralType));
  }

  if (Array.isArray(schema.anyOf)) {
    return formatUnion(
      schema.anyOf.map((item) =>
        item && typeof item === "object" ? jsonSchemaToType(item as JsonSchema) : "unknown",
      ),
    );
  }

  const typeNames = normalizeTypeNames(schema.type);
  if (typeNames.length > 1) {
    return formatUnion(
      typeNames.map((typeName) => jsonSchemaToType({ ...schema, type: typeName })),
    );
  }

  const [typeName] = typeNames;
  return formatSchemaWithType(schema, typeName);
};

const emptyContextType = "Record<string, never>";

const formatContextType = (
  defaultContext: JsonSchema | undefined,
  screenContext: JsonSchema | undefined,
): string => {
  const contextTypes = [defaultContext, screenContext]
    .filter((schema): schema is JsonSchema => schema !== undefined)
    .map(jsonSchemaToType);

  if (contextTypes.length === 0) {
    return emptyContextType;
  }

  return contextTypes.join(" & ");
};

const generateScreenTypes = (spec: SerializedTailorKitSchema): string[] => {
  const defaultContextType = spec.defaultContext
    ? jsonSchemaToType(spec.defaultContext)
    : emptyContextType;
  const lines = [
    "export interface FallbackScreenProps {",
    `  context: ${defaultContextType};`,
    "}",
    "",
    "export interface ScreenPropsByPath {",
  ];

  for (const [pathName, screenDefinition] of Object.entries(spec.screens)) {
    lines.push(`  ${JSON.stringify(pathName)}: {`);
    lines.push(`    context: ${formatContextType(spec.defaultContext, screenDefinition.context)};`);
    lines.push("  };");
  }

  lines.push("}");
  lines.push("");
  lines.push('declare module "@tailorkit/app" {');
  lines.push("  interface TailorKitFallbackScreenProps {");
  lines.push(`    context: ${defaultContextType};`);
  lines.push("  }");
  lines.push("  interface TailorKitScreens extends ScreenPropsByPath {}");
  lines.push("}");
  lines.push("");
  lines.push("export type DefaultScreenProps = FallbackScreenProps;");
  lines.push("export type ScreenPath = keyof ScreenPropsByPath & string;");
  lines.push("export type ScreenProps<TPath extends ScreenPath> = ScreenPropsByPath[TPath];");

  return lines;
};

const formatCallbackType = (
  callback: SerializedTailorKitSchema["components"][string]["callbacks"][string],
): string => {
  const args = callback.input?.map(jsonSchemaToType) ?? [];
  const output = jsonSchemaToType(callback.output);
  const returnType = callback.async ? `Promise<${output}>` : output;

  return `(${args.map((arg, index) => `arg${index}: ${arg}`).join(", ")}) => ${returnType}`;
};

const generateComponentTypes = (spec: SerializedTailorKitSchema): string => {
  const lines = [generatedHeader.trimEnd(), "", ...generateScreenTypes(spec), ""];

  for (const [name, definition] of Object.entries(spec.components)) {
    const callbackEntries = Object.entries(definition.callbacks);
    const propEntries = [
      ...definition.fieldKeys.map((fieldKey) => [fieldKey, "unknown"] as const),
      ...callbackEntries.map(
        ([callbackName, callback]) => [callbackName, formatCallbackType(callback)] as const,
      ),
    ];

    if (propEntries.length === 0) {
      lines.push(`export interface ${name}Props {}`);
    } else {
      lines.push(`export interface ${name}Props {`);
      for (const [propName, typeReference] of propEntries) {
        lines.push(`  ${formatPropertyName(propName)}?: ${typeReference};`);
      }
      lines.push("}");
    }

    lines.push("");
    if (definition.slots.length === 0) {
      lines.push(`export const ${name} = createRemoteComponent<${name}Props>("${name}");`);
    } else {
      lines.push(
        `export const ${name} = createRemoteComponent<${name}Props, ${formatStringTupleType(definition.slots)}>("${name}", {`,
      );
      lines.push(`  slots: ${formatStringArray(definition.slots)},`);
      lines.push("});");
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
};

export const generateTypes = async (loadedConfig: LoadedTailorKitConfig): Promise<string> => {
  const inputPath = path.resolve(loadedConfig.root, loadedConfig.config.components.input);
  const outputPath = path.resolve(loadedConfig.root, loadedConfig.config.components.output);
  const rawSpec = await Bun.file(inputPath).json();
  const spec = TailorKitSchemaSpec.parse(rawSpec);
  validateComponentSpec(spec);
  const generated = generateComponentTypes(spec);

  await mkdir(path.dirname(outputPath), { recursive: true });
  await Bun.write(outputPath, generated);

  return outputPath;
};
